#! /bin/sh

MAIN="LVDS-1"

bspc monitor $MAIN -d 1 2 3 4 5

bspc rule -a Steam state=floating
bspc rule -a Steam floating=on
bspc rule -a dragon state=floating
bspc rule -a wttr.in state=fullscreen
bspc rule -a electrum-ltc state=floating

bspc config border_width               4
bspc config window_gap                 8

bspc config split_ratio                0.5
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config single_monocle             false
bspc config focus_follows_pointer      true
bspc config click_to_focus             button1

bspc config pointer_action1            move
bspc config pointer_action2            resize_side
bspc config pointer_action3            resize_corner
bspc config remove_unplugged_monitors  true
bspc config remove_disabled_monitors   true

bspc config focused_border_color       "#DDB6F2"
bspc config normal_border_color        "#1E1E2E"
bspc config active_border_color        "#DDB6F2"
bspc config presel_feedback_color      "#ABE9B3"


export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
